export const state = () => ({
    languages: [
        'Bulgarian',
        'Croatian',
        'Czech',
        'Danish',
        'Dutch',
        'English',
        'Estonian',
        'Finnish',
        'French',
        'German',
        'Greek',
        'Hungarian',
        'Icelandic',
        'Irish',
        'Italian',
        'Latvian',
        'Lithuanian',
        'Luxembourgish',
        'Maltese',
        'Norwegian',
        'Polish',
        'Portuguese',
        'Romanian',
        'Spanish',
        'Swedish',
        'Swiss German',
    ]
})