# Generated by Django 2.2.6 on 2019-10-12 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applicationLink',
            field=models.CharField(default='/apply', max_length=140),
            preserve_default=False,
        ),
    ]
