# Generated by Django 2.2.6 on 2019-10-31 05:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_applicationlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='applicationLink',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=140), size=26),
        ),
    ]
